### ISSUE TITLE
socket.timeout: timed out when trying to tune a channel during boot-up

### ISSUE THREAD

**Issue by manu3b1** [AkA57/liveboxtvuhd#13]
When executing this script:

```
  allume_liveboxplay:
    sequence:
    - alias: Wake-On-LAN in case of deep sleep
      service: switch.turn_on
      entity_id: switch.wol_liveboxplay
    - wait_template: '{{ states("media_player.liveboxplay") != "unknown" }}'
      continue_on_timeout: false
      timeout: '150'
    - service: media_player.turn_on
      entity_id: media_player.liveboxplay
    - service: media_player.select_source
      data:
        entity_id: media_player.liveboxplay
        source: "FRANCE 3"
```

Got this log:
```
2021-02-14 17:38:40 INFO (MainThread) [homeassistant.components.script.allume_liveboxplay] Allume LiveboxPlay: Executing step Turn On
2021-02-14 17:38:40 INFO (MainThread) [homeassistant.components.script.allume_liveboxplay] Allume LiveboxPlay: Executing step call service
2021-02-14 17:38:40 INFO (SyncWorker_0) [custom_components.liveboxtvuhd.client] Tune to FRANCE 3
2021-02-14 17:38:43 ERROR (MainThread) [homeassistant.components.script.allume_liveboxplay] Allume LiveboxPlay: Error executing script. Unexpected error for call_service at pos 4: HTTPConnectionPool(host='orange.home', port=8080): Read timed out. (read timeout=3)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='orange.home', port=8080): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 254, in _async_step
    await getattr(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 464, in _async_call_service_step
    await service_task
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/media_player/__init__.py", line 640, in async_select_source
    await self.hass.async_add_executor_job(self.select_source, source)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/liveboxtvuhd/media_player.py", line 274, in select_source
    self._client.channel_name = source
  File "/home/homeassistant/.homeassistant/custom_components/liveboxtvuhd/client.py", line 189, in channel_name
    self.set_channel_by_name(value)
  File "/home/homeassistant/.homeassistant/custom_components/liveboxtvuhd/client.py", line 329, in set_channel_by_name
    return self.set_channel_by_id(epg_id)
  File "/home/homeassistant/.homeassistant/custom_components/liveboxtvuhd/client.py", line 323, in set_channel_by_id
    resp = requests.get(url, timeout=self.timeout)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='orange.home', port=8080): Read timed out. (read timeout=3)
2021-02-14 17:38:43 ERROR (MainThread) [homeassistant.components.script.allume_la_tele] Allume la Télé: Error executing script. Unexpected error for call_service at pos 6: HTTPConnectionPool(host='orange.home', port=8080): Read timed out. (read timeout=3)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='orange.home', port=8080): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 254, in _async_step
    await getattr(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 467, in _async_call_service_step
    await self._async_run_long_action(service_task)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 426, in _async_run_long_action
    long_task.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/script/__init__.py", line 215, in service_handler
    await script_entity.async_turn_on(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/script/__init__.py", line 320, in async_turn_on
    await coro
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 1033, in async_run
    await asyncio.shield(run.async_run())
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 246, in async_run
    await self._async_step(log_exceptions=False)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 254, in _async_step
    await getattr(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 464, in _async_call_service_step
    await service_task
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/media_player/__init__.py", line 640, in async_select_source
    await self.hass.async_add_executor_job(self.select_source, source)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/liveboxtvuhd/media_player.py", line 274, in select_source
    self._client.channel_name = source
  File "/home/homeassistant/.homeassistant/custom_components/liveboxtvuhd/client.py", line 189, in channel_name
    self.set_channel_by_name(value)
  File "/home/homeassistant/.homeassistant/custom_components/liveboxtvuhd/client.py", line 329, in set_channel_by_name
    return self.set_channel_by_id(epg_id)
  File "/home/homeassistant/.homeassistant/custom_components/liveboxtvuhd/client.py", line 323, in set_channel_by_id
    resp = requests.get(url, timeout=self.timeout)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='orange.home', port=8080): Read timed out. (read timeout=3)
```

Workaround: add a new step in the script waiting for "Source != ""):
```
  allume_liveboxplay:
    sequence:
    - alias: Wake-On-LAN in case of deep sleep
      service: switch.turn_on
      entity_id: switch.wol_liveboxplay
    - wait_template: '{{ states("media_player.liveboxplay") != "unknown" }}'
      continue_on_timeout: false
      timeout: '150'
    - alias: service: media_player.turn_on
      entity_id: media_player.liveboxplay
    - wait_template: '{{ state_attr("media_player.liveboxplay", "source") != "" }}'
      continue_on_timeout: false
      timeout: '60'
    - service: media_player.select_source
      data:
        entity_id: media_player.liveboxplay
        source: "FRANCE 3"
```

**Comment by AkA57** [comment]
Hello,

Try to reproduce this behavior with my Livebox UHD on HA core-2021.2.3, and I didn't get error.

```
allume_liveboxplay:
  sequence:
  - service: media_player.turn_on
    entity_id: media_player.livebox
  - service: media_player.select_source
    data:
      entity_id: media_player.livebox
      source: "FRANCE 3"  
```
```
2021-02-14 21:29:09 INFO (MainThread) [homeassistant.components.script.allume_liveboxplay] allume_liveboxplay: Running script sequence
2021-02-14 21:29:09 INFO (MainThread) [homeassistant.components.script.allume_liveboxplay] allume_liveboxplay: Executing step call service
2021-02-14 21:29:09 INFO (SyncWorker_1) [custom_components.liveboxtvuhd.client] Press key POWER
2021-02-14 21:29:11 INFO (SyncWorker_1) [custom_components.liveboxtvuhd.client] Press key OK
2021-02-14 21:29:11 INFO (SyncWorker_1) [custom_components.liveboxtvuhd.client] Tune to FRANCE 3
```
=>  This script turn on the livebox and switch to FRANCE 3 without any problem.

```
allume_liveboxplay2:
  sequence:
  - service: media_player.select_source
    data:
      entity_id: media_player.livebox
      source: "FRANCE 3" 
```   
```
2021-02-14 21:09:21 INFO (MainThread) [homeassistant.components.script.allume_liveboxplay2] allume_liveboxplay2: Running script sequence
2021-02-14 21:09:21 INFO (MainThread) [homeassistant.components.script.allume_liveboxplay2] allume_liveboxplay2: Executing step call service
2021-02-14 21:09:21 INFO (SyncWorker_2) [custom_components.liveboxtvuhd.client] Tune to FRANCE 3        
``` 
=> This script also swicth on the livebox, just by changing the source, maybe you should try ?

**Comment by manu3b1** [comment]
I use a LiveboxPlay.
The starting point is a livebox off.

**Comment by AkA57** [comment]
Do you use the energy-saving mode ? https://assistance.orange.fr/tv-decodeur/tous-les-decodeurs/installer-et-utiliser/parametrer-la-tv-d-orange/autres-reglages/decodeur-livebox-play-regler-le-mode-economie-d-energie_24696-25242#:~:text=Acc%C3%A9der%20%C3%A0%20vos%20r%C3%A9glages,Validez%20par%20OK.

**Comment by manu3b1** [comment]
Yes, and a master switch to cut-off the whole Home Cinema.

**Comment by AkA57** [comment]
Hello,
I just have a test with energy-saving mode and WOL.
```
2021-02-15 10:56:35 => Send WOL packet
2021-02-15 10:57:47 => media_player available
2021-02-15 10:57:59 => channel available
```
It took 72 seconds to start the livebox and 12 additionnals seconds to make the channel service available.

So this is not a bug, it's just the way the livebox work. media_player is available but the livebox has not yet stated all associated services and you get a timeout if you try to select a channel.

**Comment by manu3b1** [comment]
Hello,
On my side, I've increased the timeout to 60s and added a 2nd tuneOn after the 1rst one.
```
2021-02-15 13:10:20 DEBUG (SyncWorker_2) [custom_components.liveboxtvuhd.client] Refresh Orange API data
2021-02-15 13:10:20 DEBUG (SyncWorker_2) [custom_components.liveboxtvuhd.client] Refresh Orange API data: media_state: NA
2021-02-15 13:10:20 INFO (MainThread) [homeassistant.components.script.allume_liveboxplay] Allume LiveboxPlay: Executing step Turn On
2021-02-15 13:10:20 DEBUG (SyncWorker_1) [custom_components.liveboxtvuhd.client] Refresh Orange API data
2021-02-15 13:10:20 DEBUG (SyncWorker_1) [custom_components.liveboxtvuhd.client] Refresh Orange API data: media_state: NA
2021-02-15 13:10:20 INFO (MainThread) [homeassistant.components.script.allume_liveboxplay] Allume LiveboxPlay: Executing step call service
2021-02-15 13:10:20 INFO (SyncWorker_5) [custom_components.liveboxtvuhd.client] Tune to FRANCE 3
2021-02-15 13:10:20 DEBUG (SyncWorker_5) [custom_components.liveboxtvuhd.client] EPG ID string: ********80
2021-02-15 13:10:30 DEBUG (SyncWorker_12) [custom_components.liveboxtvuhd.client] Refresh Orange API data
2021-02-15 13:10:30 DEBUG (SyncWorker_12) [custom_components.liveboxtvuhd.client] Refresh Orange API data: media_state: NA
2021-02-15 13:10:30 INFO (MainThread) [homeassistant.components.script.allume_liveboxplay] Allume LiveboxPlay: Executing step call service
2021-02-15 13:10:30 INFO (SyncWorker_14) [custom_components.liveboxtvuhd.client] Tune to TF1
2021-02-15 13:10:30 DEBUG (SyncWorker_14) [custom_components.liveboxtvuhd.client] EPG ID string: *******192
2021-02-15 13:10:30 DEBUG (SyncWorker_9) [custom_components.liveboxtvuhd.client] Refresh Orange API data
2021-02-15 13:10:31 DEBUG (SyncWorker_9) [custom_components.liveboxtvuhd.client] Refresh Orange API data: media_state: NA
```
We can see that the Livebox HTTP server is stuck during 10s before replying the the 1rst tuneOn, then the second one is instantaneous.

So, we are aligned and my WA looks appropriate.
But do we want to let the script die with a Python Error, or handle gently the timeout?

**Comment by AkA57** [comment]
Can you try with v1.0.0-beta.1

**Comment by manu3b1** [comment]
I get this error when starting HA with Livebox off:
```
/usr/local/lib/python3.8/asyncio/events.py:81: RuntimeWarning: coroutine 'ServiceRegistry._execute_service' was never awaited
  self._context.run(self._callback, *self._args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
HTTPConnectionPool(host='orange.home', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x35bbc7d8>, 'Connection to orange.home timed out. (connect timeout=3)'))
Fatal Python error: Aborted
```

**Comment by AkA57** [comment]
Thanks,

v1.0.0-beta.2 look good for me now, it handle every errors (connection refused, timeout) during boot phase

```
2021-02-16 14:46:05 DEBUG (SyncWorker_3) [custom_components.liveboxtvuhd.client] Refresh Orange API data
2021-02-16 14:46:05 DEBUG (SyncWorker_3) [custom_components.liveboxtvuhd.client] Request Livebox operation 10
2021-02-16 14:46:05 ERROR (SyncWorker_3) [custom_components.liveboxtvuhd.client] HTTPConnectionPool(host='172.17.31.2', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x148e08941f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-02-16 14:46:15 DEBUG (SyncWorker_0) [custom_components.liveboxtvuhd.client] Refresh Orange API data
2021-02-16 14:46:15 DEBUG (SyncWorker_0) [custom_components.liveboxtvuhd.client] Request Livebox operation 10
2021-02-16 14:46:15 DEBUG (SyncWorker_0) [custom_components.liveboxtvuhd.client] Livebox: {'result': {'responseCode': '0', 'message': 'ok', 'data': {'osdContext': '', 'playedMediaType': 'NA', 'playedMediaState': 'NA', 'playedMediaId': '', 'playedMediaContextId': '', 'playedMediaPosition': 'NA', 'timeShiftingState': 'NA', 'macAddress': 'A8:9A:93:EF:5F:D9', 'wolSupport': '0', 'friendlyName': 'Decodeur TV UHD', 'activeStandbyState': '0'}}}
2021-02-16 14:46:21 DEBUG (SyncWorker_4) [custom_components.liveboxtvuhd.client] Tune to channel TF1, epg_id *******192
2021-02-16 14:46:21 DEBUG (SyncWorker_4) [custom_components.liveboxtvuhd.client] Request Livebox operation 09
2021-02-16 14:46:24 ERROR (SyncWorker_4) [custom_components.liveboxtvuhd.client] HTTPConnectionPool(host='172.17.31.2', port=8080): Read timed out. (read timeout=3)
2021-02-16 14:46:24 DEBUG (SyncWorker_3) [custom_components.liveboxtvuhd.client] Refresh Orange API data
2021-02-16 14:46:24 DEBUG (SyncWorker_3) [custom_components.liveboxtvuhd.client] Request Livebox operation 10
2021-02-16 14:46:24 DEBUG (SyncWorker_3) [custom_components.liveboxtvuhd.client] Livebox: {'result': {'responseCode': '0', 'message': 'ok', 'data': {'osdContext': '', 'playedMediaType': 'NA', 'playedMediaState': 'NA', 'playedMediaId': '', 'playedMediaContextId': '', 'playedMediaPosition': 'NA', 'timeShiftingState': 'NA', 'macAddress': 'A8:9A:93:EF:5F:D9', 'wolSupport': '0', 'friendlyName': 'Decodeur TV UHD', 'activeStandbyState': '0'}}}
```

**Comment by AkA57** [comment]
and also when livebox is REALLY off
```
2021-02-16 14:45:17 DEBUG (SyncWorker_4) [custom_components.liveboxtvuhd.client] Refresh Orange API data
2021-02-16 14:45:17 DEBUG (SyncWorker_4) [custom_components.liveboxtvuhd.client] Request Livebox operation 10
2021-02-16 14:45:20 ERROR (MainThread) [custom_components.liveboxtvuhd.media_player] Failed to connect to Livebox TV UHD at 172.17.31.2:8080. Please check your configuration.yaml. (HTTPConnectionPool(host='172.17.31.2', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x14ff7ea8e5e0>, 'Connection to 172.17.31.2 timed out. (connect timeout=3)')))
```

**Comment by manu3b1** [comment]
Same result on my side: everything works fine.
Thx!

**Comment by AkA57** [comment]
Thanks, I will publish a new public version.
