### ISSUE TITLE
Remote entity missing

### ISSUE THREAD

**Issue by piellick** [AkA57/liveboxtvuhd#48]
Hi, thanks for your works, great addon !

I have trouble to add remote entity, it's propably like #47  but i cannot find the answer. 

Here is my config:

```
media_player:
  - platform: liveboxtvuhd
    host: 192.168.1.20
    port: 8080
    scan_interval: 30
    country: france
    
remote:
  - platform: liveboxtvuhd
    host: 192.168.1.20
    name: livebox remote
    port: 8080
    scan_interval: 30
    country: france
```
    
my cards (media player entitie works great):

```
type: custom:mini-media-player
entity: media_player.liveboxtvuhd
volume_stateless: true
source: full
artwork: full-cover
layout_options:
  grid_columns: 4
  grid_rows: 4
service: remote.send_command
data:
  num_repeats: 1
  delay_secs: 0.4
  hold_secs: 0
  command: UP
target:
  entity_id: remote.livebox_remote
```

On HA logs:

```
Enregistreur: homeassistant.config
Source: config.py:1407
S'est produit pour la première fois: 00:41:30 (1 occurrences)
Dernier enregistrement: 00:41:30

Platform error: remote - No module named 'custom_components.liveboxtvuhd.remote'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1407, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1160, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1130, in async_get_platforms
    await self.hass.async_add_import_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1073, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1247, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1279, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.liveboxtvuhd.remote'

```
 I would gladly make a change on documentation to improve it if you need.
   
   thanks for your help.

**Comment by piellick** [comment]
Hi @PhoenixR49 wath was your solution ?

**Comment by PhoenixR49** [comment]
You must install the code from the `master` branch and not from a release.

**Comment by piellick** [comment]
You right damn :100:  thanks @PhoenixR49  !

**Comment by piellick** [comment]
@PhoenixR49 you know where  put the "Up" command ? Should a button must appear on mini media player ?  It's hard to find the info .

```
service: remote.send_command
data:
  num_repeats: 1
  delay_secs: 0.4
  hold_secs: 0
  command: UP
target:
  entity_id: remote.livebox_remote
```

**Comment by PhoenixR49** [comment]
If you'd like to use mini media player as a remote control for your set-top box, you can use the code I've created to use it as a remote control.

```yaml
type: custom:mini-media-player
entity: media_player.liveboxtvuhd
artwork: full-cover
source: full
sound_mode: full
volume_stateless: true
shortcuts:
  hide_when_off: true
  columns: 3
  label: Applications
  buttons:
    - name: VOD
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: DOWN
        hold_secs: 0
    - icon: mdi:arrow-up
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: UP
        hold_secs: 0
    - icon: mdi:record
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: DOWN
        hold_secs: 0
    - icon: mdi:arrow-left
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: LEFT
        hold_secs: 0
    - name: OK
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: OK
        hold_secs: 0
    - icon: mdi:arrow-right
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: RIGHT
        hold_secs: 0
    - type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: null
        hold_secs: 0
    - icon: mdi:arrow-down
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: DOWN
        hold_secs: 0
    - type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: null
        hold_secs: 0
    - name: 1
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: 1
        hold_secs: 0
    - name: 2
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: 2
        hold_secs: 0
    - name: 3
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: 3
        hold_secs: 0
    - name: 4
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: 4
        hold_secs: 0
    - name: 5
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: 5
        hold_secs: 0
    - name: 6
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: 6
        hold_secs: 0
    - name: 7
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: 7
        hold_secs: 0
    - name: 8
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: 8
        hold_secs: 0
    - name: 9
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: 9
        hold_secs: 0
    - name: Retour
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: BACK
        hold_secs: 0
    - name: O
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: 0
        hold_secs: 0
    - name: Menu
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command: MENU
        hold_secs: 0
    - icon: mdi:netflix
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command:
          - 6
          - 6
        hold_secs: 0
    - icon: phu:prime-video
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command:
          - 6
          - 7
        hold_secs: 0
    - icon: phu:disney-plus
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command:
          - 6
          - 8
        hold_secs: 0
    - icon: phu:paramount
      type: service
      id: remote.send_command
      data:
        entity_id: remote.livebox_remote
        command:
          - 6
          - 9
        hold_secs: 0
```

I hope you find it useful

**Comment by piellick** [comment]
so cool thanks @PhoenixR49 , it will serve for everyone !
