### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by alzalia1** [AkA57/liveboxtvuhd#50]
This integration is really great. But the logs aren't really of the same opinion...

**First error :** The media_player entity seems to be using outdated methods (there a two different warnings)

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1637
First occurred: 3:06:32 PM (1 occurrences)
Last logged: 3:06:32 PM

Entity media_player.tv_orange (<class 'custom_components.liveboxtvuhd.media_player.LiveboxTvUhdDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|TURN_ON|TURN_OFF|VOLUME_STEP|SELECT_SOURCE|PLAY: 19897>, please report it to the author of the 'liveboxtvuhd' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```
```
Logger: homeassistant.components.media_player.const
Source: helpers/deprecation.py:197
integration: Media player (documentation, issues)
First occurred: 3:06:32 PM (13 occurrences)
Last logged: 3:06:32 PM

• SUPPORT_SELECT_SOURCE was used from liveboxtvuhd, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.SELECT_SOURCE instead, please report it to the author of the 'liveboxtvuhd' custom integration
• SUPPORT_TURN_OFF was used from liveboxtvuhd, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.TURN_OFF instead, please report it to the author of the 'liveboxtvuhd' custom integration
• SUPPORT_TURN_ON was used from liveboxtvuhd, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.TURN_ON instead, please report it to the author of the 'liveboxtvuhd' custom integration
• SUPPORT_VOLUME_MUTE was used from liveboxtvuhd, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.VOLUME_MUTE instead, please report it to the author of the 'liveboxtvuhd' custom integration
• SUPPORT_VOLUME_STEP was used from liveboxtvuhd, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.VOLUME_STEP instead, please report it to the author of the 'liveboxtvuhd' custom integration
```

**Second error :** The `remote` entity cannot be activated (which is a shame, it would have been perfect if it did)

```
Logger: homeassistant.config
Source: config.py:1413
First occurred: 3:06:32 PM (1 occurrences)
Last logged: 3:06:32 PM

Platform error: remote - No module named 'custom_components.liveboxtvuhd.remote'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1413, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1100, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1147, in async_get_platforms
    await self.hass.async_add_import_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.liveboxtvuhd.remote'
```

**Third error :** Home Assistant doesn't like `fuzzywuzzy` apparently

```
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/liveboxtvuhd/client.py:12
integration: Orange Livebox TV UHD (documentation)
First occurred: 3:06:32 PM (1 occurrences)
Last logged: 3:06:32 PM

/usr/local/lib/python3.12/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
```

Overall, while the project is amazing, it seems like it won't work at all in 2025... If I knew my way around HA framework I could maybe try and fix things but hum... i don't...
So, I can only hope the maintainer of this project comes back to life !
Thanks again for this anyway, event if it ends up not working, at least it did for some time :smiling_face_with_tear:

**Comment by AkA57** [comment]
Hello Alzalia

I just remove fuzzywuzzy who's no more requested by this integration, can you try the last release (v1.1.0) ?

I run it with HA 2024.9.2 and don't have any errors with remote or media player. The main problem I have today, is that I don't own a livebox anymore, so I just "emulated it".

**Comment by alzalia1** [comment]
Hi ! 

Your commits indeed fixed most of the issues, I do see a remote (I'll have to test it when I can this evening).

The only remaining log warning is this one :

```
Logger: homeassistant.components.media_player.const
Source: helpers/deprecation.py:197
integration: Media player (documentation, issues)
First occurred: 16:48:10 (6 occurrences)
Last logged: 16:48:10

MEDIA_TYPE_CHANNEL was used from liveboxtvuhd, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.CHANNEL instead, please report it to the author of the 'liveboxtvuhd' custom integration
MEDIA_TYPE_TVSHOW was used from liveboxtvuhd, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.TVSHOW instead, please report it to the author of the 'liveboxtvuhd' custom integration
```

I personally run `HA 2024.10.3` (which I believe to be the latest version ?) So maybe that's where the warnings come from, but indeed, not owning a livebox, I can understand that testing and developping this amazing integration can be pretty hard !

**Comment by AkA57** [comment]
Hi Alzalia,

Can you have a test with version 1.2.0 ?

**Comment by alzalia1** [comment]
There doesn't seem to be any more warning ! I'll be able to test functionnalities on my tv in about one hour.

In the meantime, thank you so much for thoses fixes ! (If you decide to mark this issue as closed, I'll only create a new issue if there is a problem - otherwise I'll post here if it either works or don't ^^)

have a great day !

**Comment by alzalia1** [comment]
I can indeed use my TV through HA, both the controls and the content. So everything is absolutely perfect ! Thank you so much again !
