### ISSUE TITLE
component not loading

### ISSUE THREAD

**Issue by artiwal** [AkA57/liveboxtvuhd#6]
Home Assistant 0.109.2
System | HassOS 3.13

I have just installed Livebox TV UHD via HACS, config.yaml:
media_player:
  - platform: liveboxtvuhd
    host: x.x.x.x
    scan_interval: 30
    name: orange_livebox_play_tv

Entity not showing up at all. ha.log as below:

2020-05-02 23:40:11 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for liveboxtvuhd which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-02 23:40:11 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for liveboxtvuhd doing I/O at custom_components/liveboxtvuhd/client.py, line 56: resp = requests.get(url, params=get_params, timeout=self.timeout)
2020-05-02 23:40:11 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up liveboxtvuhd platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/liveboxtvuhd/media_player.py", line 72, in async_setup_platform
    device = LiveboxTvUhdDevice(host, port, name)
  File "/config/custom_components/liveboxtvuhd/media_player.py", line 90, in __init__
    self._client = LiveboxTvUhdClient(host, port)
  File "/config/custom_components/liveboxtvuhd/client.py", line 50, in __init__
    assert isinstance(self.info, dict), "Failed to retrive info from {}".format(self.hostname)
  File "/config/custom_components/liveboxtvuhd/client.py", line 169, in info
    return self.update()
  File "/config/custom_components/liveboxtvuhd/client.py", line 62, in update
    self._media_state = _data["playedMediaState"]
KeyError: 'playedMediaState'

**Comment by Shkrum31** [comment]
Hi, component works well (and thanks a lot for that !) but with I/O errors, that appeared with the 109.1 HA update.

Détails du journal ( WARNING )
Logger: homeassistant.util.async_
Source: util/async_.py:120 
First occurred: 2:57:12 (5 occurrences) 
Last logged: 2:57:45

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for liveboxtvuhd doing I/O at custom_components/liveboxtvuhd/client.py, line 56: resp = requests.get(url, params=get_params, timeout=self.timeout)

Thanks for your help

**Comment by AkA57** [comment]
Hello @artiwal ,
Looks like you are using a Livebox Play, not an UHD. I will try to fix it, but can you send me some information:

- Power on your Livebox and watch TF1.
- Go to http://IP_OF_LIVEBOX:8080/remoteControl/cmd?operation=10 (don't forget to replace IP_OF_LIVEBOX by the real IP).
- Copy/paste here the result.

Thank you!

**Comment by artiwal** [comment]
Hi,
The case it is not even showing under entity list and as I assume it should even if it is not connected to LiveBox. I'm in poland so I do not have TF1. Here is result when watching Comedy Central HD  (channel 18)

{ "result": { "responseCode": "0", "message": "ok", "data": { "activeStandbyState": "0", "friendlyName": "Orange TV Dekoder (Samsung ICU 100)", "macAddress": "60:C5:AD:A6:AB:A9", "osdContext": "LIVE", "playedMediaContextId": "1", "playedMediaId": "14301", "playedMediaPosition": "NA", "playedMediaState": "PLAY", "playedMediaType": "LIVE", "timeShiftingState": "0", "wolSupport": "0" } } }

**Comment by AkA57** [comment]
Hi,
Can you try with v0.0.5?
But for sure you will have problem with channel name/number. You can have a look at const.py, it has only French channel

**Comment by artiwal** [comment]
Thank you. Indeed I can see entity now and I can see status of playing. After slight epg codes update I can see what channel is played (of course see no current show) and I can even change it but other controls are not working at all... No power, volume, next/prev channel... Key codes seems to be the same. I have tried checking your client.py but I'm not python guy but it seemed OKfor me...
To do power on I need to issue: 
http://x.x.x.x:8080/remoteControl/cmd?operation=01&key=116&mode=0
Is it evoked by your code the same way? Any hint will be appreciated so I can adjust it for my needs if you do not mind :)

**Comment by AkA57** [comment]
It send http://x.x.x.x:8080/remoteControl/cmd?operation=1&key=116&mode=0 to power on/off.
Maybe it's not working with operation=1 on your livebox and it should be operation=01 ?

**Comment by alhousez** [comment]
Hello,

I have the same problem with

Home assistant 0.109.6 on Windows 10
Livebox TV UHD 0.0.5
player: ihd92

During the reboot:
020-05-19 00:13:51 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up liveboxtvuhd platform for media_player
Traceback (most recent call last):
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\MyHome\AppData\Roaming\.homeassistant\custom_components\liveboxtvuhd\media_player.py", line 73, in async_setup_platform
    device = LiveboxTvUhdDevice(host, port, name)
  File "C:\Users\MyHome\AppData\Roaming\.homeassistant\custom_components\liveboxtvuhd\media_player.py", line 91, in __init__
    self._client = LiveboxTvUhdClient(host, port)
  File "C:\Users\MyHome\AppData\Roaming\.homeassistant\custom_components\liveboxtvuhd\client.py", line 57, in __init__
    assert isinstance(self.info, dict), "Failed to retrive info from {}".format(self.hostname)
  File "C:\Users\MyHome\AppData\Roaming\.homeassistant\custom_components\liveboxtvuhd\client.py", line 222, in info
    return self.update()
  File "C:\Users\MyHome\AppData\Roaming\.homeassistant\custom_components\liveboxtvuhd\client.py", line 63, in update
    resp = requests.get(url, params=get_params, timeout=self.timeout)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)...

My configuration.yaml : 
media_player:
  - platform: liveboxtvuhd
    name: Livebox_Play
    host: 192.168.1.13
    scan_interval: 10


Result of http://192.168.1.13:8080/remoteControl/cmd?operation=10
{
    "result":
    {
        "responseCode": "0",
        "message": "ok",
        "data":
        {"osdContext": "LIVE",
"playedMediaType": "LIVE",
"playedMediaState": "PLAY",
"playedMediaId": "192",
"playedMediaContextId": "NA",
"playedMediaPosition": "NA",
"timeShiftingState": "0",
"macAddress": "18:62:2C:EC:FD:AB",
"wolSupport": "0",
"friendlyName": "decodeur TV",
"activeStandbyState": "0"
}
    }
}

Thanks for your help

**Comment by AkA57** [comment]
Hello @alhousez 
Thanks for your feedback.
Can you provide the full stack of this error ? I need to know what is displayed after:
packages\urllib3\connectionpool.py", line 392, in _make_request
conn.request(method, url, **httplib_request_kw)...

**Comment by alhousez** [comment]
Hello @AkA57

I just migrated HASS to 0.110 and  liveboxtvuhd to 0.0.6 and messages are

2020-05-24 14:12:04 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up liveboxtvuhd platform for media_player
Traceback (most recent call last):
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\MyHome\AppData\Roaming\.homeassistant\custom_components\liveboxtvuhd\media_player.py", line 73, in async_setup_platform
    device = LiveboxTvUhdDevice(host, port, name)
  File "C:\Users\MyHome\AppData\Roaming\.homeassistant\custom_components\liveboxtvuhd\media_player.py", line 91, in __init__
    self._client = LiveboxTvUhdClient(host, port)
  File "C:\Users\MyHome\AppData\Roaming\.homeassistant\custom_components\liveboxtvuhd\client.py", line 57, in __init__
    assert isinstance(self.info, dict), "Failed to retrive info from {}".format(self.hostname)
  File "C:\Users\MyHome\AppData\Roaming\.homeassistant\custom_components\liveboxtvuhd\client.py", line 222, in info
    return self.update()
  File "C:\Users\MyHome\AppData\Roaming\.homeassistant\custom_components\liveboxtvuhd\client.py", line 63, in update
    resp = requests.get(url, params=get_params, timeout=self.timeout)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\http\client.py", line 1251, in _send_request
    self.putrequest(method, url, **skips)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 199, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\homeassistant\util\async_.py", line 120, in protected_loop_func
    check_loop()
  File "c:\users\myhome\appdata\local\programs\python\python38\lib\site-packages\homeassistant\util\async_.py", line 91, in check_loop
    raise RuntimeError(
RuntimeError: Detected I/O inside the event loop. This is causing stability issues. Please report issue
2020-05-24 14:12:04 INFO (MainThread) [homeassistant.setup] Setting up zeroconf

**Comment by AkA57** [comment]
Thanks.
Please try v0.07

**Comment by alhousez** [comment]
It works with v0.07.
Thanks
